### ISSUE TITLE
error when running meteor

### ISSUE THREAD

**Issue by alexfrieden** [VeliovGroup/ostrio-Neo4jreactivity#19]
Getting the following error and trying to find what the issue might be:

```
W20150301-10:59:41.459(-5)? (STDERR)
W20150301-10:59:41.460(-5)? (STDERR) /Users/alexander.frieden/.meteor/packages/meteor-tool/.1.0.38.dyr4zt++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150301-10:59:41.460(-5)? (STDERR) 						throw(ex);
W20150301-10:59:41.461(-5)? (STDERR) 						      ^
W20150301-10:59:41.467(-5)? (STDERR) TypeError: Object #<Object> has no method 'npmRequire'
W20150301-10:59:41.468(-5)? (STDERR)     at Meteor.neo4j (packages/ostrio:neo4jreactivity/ostrio:neo4jreactivity_driver.js:12:1)
W20150301-10:59:41.468(-5)? (STDERR)     at /Users/alexander.frieden/projects/core-modules/meteor-app/.meteor/local/build/programs/server/packages/ostrio_neo4jreactivity.js:707:4
W20150301-10:59:41.468(-5)? (STDERR)     at /Users/alexander.frieden/projects/core-modules/meteor-app/.meteor/local/build/programs/server/packages/ostrio_neo4jreactivity.js:822:3
W20150301-10:59:41.468(-5)? (STDERR)     at /Users/alexander.frieden/projects/core-modules/meteor-
app/.meteor/local/build/programs/server/boot.js:175:10
W20150301-10:59:41.468(-5)? (STDERR)     at Array.forEach (native)
W20150301-10:59:41.468(-5)? (STDERR)     at Function._.each._.forEach (/Users/alexander.frieden/.meteor/packages/meteor-tool/.1.0.38.dyr4zt++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150301-10:59:41.468(-5)? (STDERR)     at /Users/alexander.frieden/projects/core-modules/meteor-app/.meteor/local/build/programs/server/boot.js:86:5
```

Any thoughts on what this might be?

**Comment by dr-dimitru** [comment]
Hi,

Somewhy driver can't find npmRequire method. Try to run upgrade on meteor and/or reinstall package.

Also try to install meteorhacks:npm separately 

We have never meet this issue before.

**Comment by dr-dimitru** [comment]
Also will publish an update today to switch to native NPM.require

**Comment by dr-dimitru** [comment]
@alexfrieden thank you for your report, issue fixed in 50779acc7a4155f3cd87e78de59c99b58903d666, please update

**Comment by alexfrieden** [comment]
@dr-dimitru just by doing:
```
meteor remove ostrio:neo4jreactivity
meteor add ostrio:neo4jreactivity
```
right?

**Comment by dr-dimitru** [comment]
Nope.
`meteor update`
